version: '3'
services:
  mongo.tfm.com:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  springboot: 
    image: 005269061637.dkr.ecr.eu-west-1.amazonaws.com/small_comerce_api_rest:$change
    ports:
      - "90:8080"
    depends_on:
      - mongo.tfm.com
volumes:
  logs: {}